### ISSUE TITLE
Sign in button does nothing

### ISSUE THREAD

**Issue by dresswithpockets** [patriksvensson/ghostly#3]
**Describe the bug**
Attempting to log in by going through the sign in flow. "Sign in using external browser" button closes the dialogue and does nothing afterwards.

**To Reproduce**
1. Click on "Sign in to GitHub"
2. Click on "Sign in using external browser"
3. Nothing happens

**Expected behavior**
It opens up an auth flow in my browser.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows Pro x64
 - Version: 10.0.19042 Build 19042

**Comment by NRKirby** [comment]
I had the same issue yesterday after installing Ghostly from the Windows 10 store:

OS: Windows 10 Pro x64
OS build: 19042.1415

I've now uninstalled the Windows store version and running a version built from source in Visual Studio

**Comment by patriksvensson** [comment]
@NRKirby Very strange. It's the same version in the store as this repository `1.17.0`, and both works for me locally.
I will investigate this a bit when I have some spare time.

**Comment by patriksvensson** [comment]
@NRKirby Actually, I was able to reproduce this. Will fix and push a new version

**Comment by NRKirby** [comment]
@patriksvensson that's great, I'll keep an eye out for the change. 

BTW this is an awesome project and I'd love to contribute! There's a lot in here I'm interested in and I'm spending time now to see how it's implemented. I'll keep an eye out for issues I can contribute to :smiley:

**Comment by patriksvensson** [comment]
@dresswithpockets @NRKirby It was a [PEBKAC](https://en.wiktionary.org/wiki/PEBCAK) error. I've uploaded a new version (`1.18.0`) which should be available shortly.

**Comment by patriksvensson** [comment]
@dresswithpockets @dresswithpockets Update is available on Windows Store now.
